version: '3'
services:
    gm-backend:
        build:
            context: route-consumer/
            dockerfile: Dockerfile
        container_name: gm-backend
        ports:
            - "9090:9090"
        networks: 
            - minha-rede

    coordinate-sender:
        build:
            context: xmlreader/
            dockerfile: Dockerfile
        container_name: desafio-gm-route-sender
        environment:
            - API_HOST=192.168.1.8
            - API_PORT=9090
        networks: 
            - minha-rede
        depends_on:
            - gm-backend

networks: 
    minha-rede:
        driver: bridge